# Generated by Django 5.0.4 on 2024-07-05 05:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transfer_files_to_model', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reportruskvolumecheck',
            name='Apartment_building',
            field=models.BooleanField(null=True, verbose_name='Есть МОП'),
        ),
    ]
